[2024-01-23T17:07:31.915+0200] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: write_to_postgresql.populate_table manual__2024-01-23T15:07:27.072632+00:00 [queued]>
[2024-01-23T17:07:31.921+0200] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: write_to_postgresql.populate_table manual__2024-01-23T15:07:27.072632+00:00 [queued]>
[2024-01-23T17:07:31.921+0200] {taskinstance.py:2171} INFO - Starting attempt 1 of 1
[2024-01-23T17:07:31.936+0200] {taskinstance.py:2192} INFO - Executing <Task(PostgresOperator): populate_table> on 2024-01-23 15:07:27.072632+00:00
[2024-01-23T17:07:31.937+0200] {standard_task_runner.py:60} INFO - Started process 35185 to run task
[2024-01-23T17:07:31.940+0200] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'write_to_postgresql', 'populate_table', 'manual__2024-01-23T15:07:27.072632+00:00', '--job-id', '272', '--raw', '--subdir', 'DAGS_FOLDER/write_to_postgresql.py', '--cfg-path', '/tmp/tmp6m_x561l']
[2024-01-23T17:07:31.941+0200] {standard_task_runner.py:88} INFO - Job 272: Subtask populate_table
[2024-01-23T17:07:31.977+0200] {task_command.py:423} INFO - Running <TaskInstance: write_to_postgresql.populate_table manual__2024-01-23T15:07:27.072632+00:00 [running]> on host DESKTOP-9NHC01K.
[2024-01-23T17:07:32.029+0200] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='write_to_postgresql' AIRFLOW_CTX_TASK_ID='populate_table' AIRFLOW_CTX_EXECUTION_DATE='2024-01-23T15:07:27.072632+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-01-23T15:07:27.072632+00:00'
[2024-01-23T17:07:32.030+0200] {sql.py:276} INFO - Executing: 
            INSERT INTO employees(id,name) VALUES
            (1,'Ahmed'),
            (2,'Ali') ,
            (3,'Rami'),
            (4,'Adel');
            
[2024-01-23T17:07:32.033+0200] {base.py:83} INFO - Using connection ID 'my_postgres_cnn' for task execution.
[2024-01-23T17:07:32.056+0200] {base.py:83} INFO - Using connection ID 'my_postgres_cnn' for task execution.
[2024-01-23T17:07:32.068+0200] {sql.py:450} INFO - Running statement: 
            INSERT INTO employees(id,name) VALUES
            (1,'Ahmed'),
            (2,'Ali') ,
            (3,'Rami'),
            (4,'Adel');
            , parameters: None
[2024-01-23T17:07:32.073+0200] {sql.py:459} INFO - Rows affected: 4
[2024-01-23T17:07:32.079+0200] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=write_to_postgresql, task_id=populate_table, execution_date=20240123T150727, start_date=20240123T150731, end_date=20240123T150732
[2024-01-23T17:07:32.112+0200] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-01-23T17:07:32.124+0200] {taskinstance.py:3281} INFO - 1 downstream tasks scheduled from follow-on schedule check
