[2024-01-18T15:56:51.516+0200] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: write_to_postgresql.populate_table manual__2024-01-18T13:56:47.102646+00:00 [queued]>
[2024-01-18T15:56:51.521+0200] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: write_to_postgresql.populate_table manual__2024-01-18T13:56:47.102646+00:00 [queued]>
[2024-01-18T15:56:51.521+0200] {taskinstance.py:2171} INFO - Starting attempt 1 of 1
[2024-01-18T15:56:51.537+0200] {taskinstance.py:2192} INFO - Executing <Task(PostgresOperator): populate_table> on 2024-01-18 13:56:47.102646+00:00
[2024-01-18T15:56:51.539+0200] {standard_task_runner.py:60} INFO - Started process 18921 to run task
[2024-01-18T15:56:51.542+0200] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'write_to_postgresql', 'populate_table', 'manual__2024-01-18T13:56:47.102646+00:00', '--job-id', '214', '--raw', '--subdir', 'DAGS_FOLDER/write_to_postgresql.py', '--cfg-path', '/tmp/tmpnswe3vux']
[2024-01-18T15:56:51.543+0200] {standard_task_runner.py:88} INFO - Job 214: Subtask populate_table
[2024-01-18T15:56:51.573+0200] {task_command.py:423} INFO - Running <TaskInstance: write_to_postgresql.populate_table manual__2024-01-18T13:56:47.102646+00:00 [running]> on host DESKTOP-9NHC01K.
[2024-01-18T15:56:51.626+0200] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='write_to_postgresql' AIRFLOW_CTX_TASK_ID='populate_table' AIRFLOW_CTX_EXECUTION_DATE='2024-01-18T13:56:47.102646+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-01-18T13:56:47.102646+00:00'
[2024-01-18T15:56:51.626+0200] {sql.py:276} INFO - Executing: 
            INSERT INTO employees(id,name) VALUES
            (1,'Ahmed'),
            (2,'Ali') ,
            (3,'Rami'),
            (4,'Adel');
            
[2024-01-18T15:56:51.631+0200] {base.py:83} INFO - Using connection ID 'my_postgres_cnn' for task execution.
[2024-01-18T15:56:51.656+0200] {base.py:83} INFO - Using connection ID 'my_postgres_cnn' for task execution.
[2024-01-18T15:56:51.669+0200] {sql.py:450} INFO - Running statement: 
            INSERT INTO employees(id,name) VALUES
            (1,'Ahmed'),
            (2,'Ali') ,
            (3,'Rami'),
            (4,'Adel');
            , parameters: None
[2024-01-18T15:56:51.670+0200] {sql.py:459} INFO - Rows affected: 4
[2024-01-18T15:56:51.676+0200] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=write_to_postgresql, task_id=populate_table, execution_date=20240118T135647, start_date=20240118T135651, end_date=20240118T135651
[2024-01-18T15:56:51.713+0200] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-01-18T15:56:51.723+0200] {taskinstance.py:3281} INFO - 1 downstream tasks scheduled from follow-on schedule check
