[2024-01-18T12:48:16.874+0200] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: transformation_with_task_flow_api.Filtering.filter_by_region manual__2024-01-18T10:48:04.506494+00:00 [queued]>
[2024-01-18T12:48:16.879+0200] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: transformation_with_task_flow_api.Filtering.filter_by_region manual__2024-01-18T10:48:04.506494+00:00 [queued]>
[2024-01-18T12:48:16.879+0200] {taskinstance.py:2171} INFO - Starting attempt 1 of 1
[2024-01-18T12:48:16.893+0200] {taskinstance.py:2192} INFO - Executing <Task(_PythonDecoratedOperator): Filtering.filter_by_region> on 2024-01-18 10:48:04.506494+00:00
[2024-01-18T12:48:16.897+0200] {standard_task_runner.py:60} INFO - Started process 17520 to run task
[2024-01-18T12:48:16.899+0200] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'transformation_with_task_flow_api', 'Filtering.filter_by_region', 'manual__2024-01-18T10:48:04.506494+00:00', '--job-id', '194', '--raw', '--subdir', 'DAGS_FOLDER/applying_task_flow_api.py', '--cfg-path', '/tmp/tmp4_6epv8l']
[2024-01-18T12:48:16.900+0200] {standard_task_runner.py:88} INFO - Job 194: Subtask Filtering.filter_by_region
[2024-01-18T12:48:16.933+0200] {task_command.py:423} INFO - Running <TaskInstance: transformation_with_task_flow_api.Filtering.filter_by_region manual__2024-01-18T10:48:04.506494+00:00 [running]> on host DESKTOP-9NHC01K.
[2024-01-18T12:48:17.051+0200] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='transformation_with_task_flow_api' AIRFLOW_CTX_TASK_ID='Filtering.filter_by_region' AIRFLOW_CTX_EXECUTION_DATE='2024-01-18T10:48:04.506494+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-01-18T10:48:04.506494+00:00'
[2024-01-18T12:48:17.053+0200] {taskinstance.py:2699} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/mahmoud/airflow_env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/mahmoud/airflow_env/lib/python3.10/site-packages/airflow/decorators/base.py", line 242, in execute
    return_value = super().execute(context)
  File "/home/mahmoud/airflow_env/lib/python3.10/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/mahmoud/airflow_env/lib/python3.10/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/mahmoud/airflow/dags/applying_task_flow_api.py", line 38, in filter_by_region
    df=pd.read_json(data)
  File "/home/mahmoud/airflow_env/lib/python3.10/site-packages/pandas/io/json/_json.py", line 780, in read_json
    json_reader = JsonReader(
  File "/home/mahmoud/airflow_env/lib/python3.10/site-packages/pandas/io/json/_json.py", line 893, in __init__
    data = self._get_data_from_filepath(filepath_or_buffer)
  File "/home/mahmoud/airflow_env/lib/python3.10/site-packages/pandas/io/json/_json.py", line 933, in _get_data_from_filepath
    self.handles = get_handle(
  File "/home/mahmoud/airflow_env/lib/python3.10/site-packages/pandas/io/common.py", line 709, in get_handle
    if _is_binary_mode(path_or_buf, mode) and "b" not in mode:
  File "/home/mahmoud/airflow_env/lib/python3.10/site-packages/pandas/io/common.py", line 1171, in _is_binary_mode
    return isinstance(handle, _get_binary_io_classes()) or "b" in getattr(
TypeError: argument of type 'method' is not iterable
[2024-01-18T12:48:17.056+0200] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=transformation_with_task_flow_api, task_id=Filtering.filter_by_region, execution_date=20240118T104804, start_date=20240118T104816, end_date=20240118T104817
[2024-01-18T12:48:17.073+0200] {standard_task_runner.py:107} ERROR - Failed to execute job 194 for task Filtering.filter_by_region (argument of type 'method' is not iterable; 17520)
[2024-01-18T12:48:17.112+0200] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-01-18T12:48:17.123+0200] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
